"""Add all tables

Revision ID: d30a7d28fe0a
Revises:
Create Date: 2026-09-23 13:33:41.989503

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d30a7d28fe0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AcademicTerm",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session", sa.String(), nullable=False),
        sa.Column(
            "term",
            sa.Enum("FIRST", "SECOND", "THIRD", name="Term", create_constraint=True),
            nullable=False,
        ),
        sa.Column("startsOn", sa.Date(), nullable=False),
        sa.Column("endsOn", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session", "term"),
    )
    op.create_table(
        "Achievement",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("criteriaType", sa.String(), nullable=False),
        sa.Column("criteriaValue", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "Admin",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("passwordHash", sa.String(), nullable=False),
        sa.Column("isOwner", sa.Boolean(), nullable=False),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column("lastLoginAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("createdById", sa.String(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["createdById"],
            ["Admin.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "Announcement",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("audience", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "SENDING",
                "SENT",
                "CANCELLED",
                name="AnnouncementStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expiresAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recipientCount", sa.Integer(), nullable=False),
        sa.Column("sentCount", sa.Integer(), nullable=False),
        sa.Column("failedCount", sa.Integer(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completedAt", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "JambCombination",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("courseOfStudy", sa.String(), nullable=False),
        sa.Column("faculty", sa.String(), nullable=False),
        sa.Column(
            "requiredSubjects", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "alternateSubjects", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "PaystackEvent",
        sa.Column("eventKey", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("eventKey"),
    )
    op.create_table(
        "ProviderState",
        sa.Column(
            "provider",
            sa.Enum("SDASH", name="QuestionProvider", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "circuit",
            sa.Enum(
                "OK",
                "EXHAUSTED",
                "BLOCKED",
                name="ProviderCircuitState",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("cooldownUntil", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creditsRemaining", sa.Integer(), nullable=True),
        sa.Column("probeInFlight", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "School",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column(
            "schoolType",
            sa.Enum("PUBLIC", "PRIVATE", name="SchoolType", create_constraint=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Subject",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("isWaec", sa.Boolean(), nullable=False),
        sa.Column("isJamb", sa.Boolean(), nullable=False),
        sa.Column("isNeco", sa.Boolean(), nullable=False),
        sa.Column(
            "trackCategory",
            sa.Enum(
                "CORE",
                "SCIENCE",
                "ARTS",
                "COMMERCIAL",
                "VOCATIONAL",
                name="TrackCategory",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "VerificationToken",
        sa.Column("identifier", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("identifier", "token"),
        sa.UniqueConstraint("identifier", "token"),
    )
    op.create_table(
        "AdminAudit",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("actorId", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("entityId", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actorId"], ["Admin.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "AnnouncementDelivery",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("announcementId", sa.String(), nullable=False),
        sa.Column("subscriptionId", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "FAILED",
                "GONE",
                "CANCELLED",
                name="DeliveryStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("claimedAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["announcementId"], ["Announcement.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("announcementId", "subscriptionId"),
    )
    op.create_table(
        "Assessment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=True),
        sa.Column(
            "assessmentType",
            sa.Enum(
                "TOPIC_QUIZ",
                "SUBJECT_TEST",
                "PAST_PAPER",
                "MOCK_EXAM",
                "CBT_PRACTICE",
                "CUSTOM",
                name="AssessmentType",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "examType",
            sa.Enum(
                "WAEC",
                "JAMB",
                "NECO",
                "CUSTOM",
                name="ExamType",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("examYear", sa.Integer(), nullable=True),
        sa.Column("totalMarks", sa.Integer(), nullable=False),
        sa.Column("timeLimitMinutes", sa.Integer(), nullable=True),
        sa.Column("passMarkPercent", sa.Integer(), nullable=False),
        sa.Column("createdBy", sa.String(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "CurriculumLevel",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column(
            "classLevel",
            sa.Enum("SS1", "SS2", "SS3", name="ClassLevel", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "term",
            sa.Enum("FIRST", "SECOND", "THIRD", name="Term", create_constraint=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subjectId"], ["Subject.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subjectId", "classLevel", "term"),
    )
    op.create_table(
        "ProviderCatalogue",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("SDASH", name="QuestionProvider", create_constraint=True),
            nullable=False,
        ),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column(
            "examType",
            sa.Enum(
                "WAEC",
                "JAMB",
                "NECO",
                "CUSTOM",
                name="ExamType",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("examYear", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subjectId", "examType", "examYear"),
    )
    op.create_table(
        "ProviderFetch",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("SDASH", name="QuestionProvider", create_constraint=True),
            nullable=False,
        ),
        sa.Column("cacheKey", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SATURATED",
                "FAILED",
                name="ProviderFetchStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("startedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("drawCount", sa.Integer(), nullable=False),
        sa.Column("rawCount", sa.Integer(), nullable=False),
        sa.Column("newInLastDraw", sa.Integer(), nullable=False),
        sa.Column("promotedCount", sa.Integer(), nullable=False),
        sa.Column("rejectedCount", sa.Integer(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=True),
        sa.Column(
            "examType",
            sa.Enum(
                "WAEC",
                "JAMB",
                "NECO",
                "CUSTOM",
                name="ExamType",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("examYear", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "cacheKey"),
    )
    op.create_table(
        "SubjectResource",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "resourceType",
            sa.Enum(
                "PDF",
                "IMAGE",
                "VIDEO",
                "LINK",
                name="MaterialType",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("isFree", sa.Boolean(), nullable=False),
        sa.Column("orderIndex", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["subjectId"], ["Subject.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "User",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("passwordHash", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("STUDENT", "TEACHER", "ADMIN", name="Role", create_constraint=True),
            nullable=False,
        ),
        sa.Column("firstName", sa.String(), nullable=True),
        sa.Column("lastName", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "classLevel",
            sa.Enum("SS1", "SS2", "SS3", name="ClassLevel", create_constraint=True),
            nullable=True,
        ),
        sa.Column(
            "track",
            sa.Enum(
                "SCIENCE", "ARTS", "COMMERCIAL", name="Track", create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("schoolId", sa.String(), nullable=True),
        sa.Column(
            "tier",
            sa.Enum(
                "FREEMIUM",
                "STANDARD",
                "PREMIUM",
                name="SubscriptionTier",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("tierUpdatedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column("suspendedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspendedReason", sa.Text(), nullable=True),
        sa.Column("sessionsValidFrom", sa.DateTime(timezone=True), nullable=True),
        sa.Column("emailVerified", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["schoolId"],
            ["School.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_index(
        "User_classLevel_track_idx", "User", ["classLevel", "track"], unique=False
    )
    op.create_index("User_isActive_idx", "User", ["isActive"], unique=False)
    op.create_index("User_state_idx", "User", ["state"], unique=False)
    op.create_index("User_tier_idx", "User", ["tier"], unique=False)
    op.create_table(
        "Account",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("providerAccountId", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("token_type", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("id_token", sa.Text(), nullable=True),
        sa.Column("session_state", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "providerAccountId"),
    )
    op.create_table(
        "AnnouncementDismissal",
        sa.Column("announcementId", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["announcementId"], ["Announcement.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("announcementId", "userId"),
    )
    op.create_table(
        "AssessmentAttempt",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("assessmentId", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "COMPLETED",
                "ABANDONED",
                "TIMED_OUT",
                name="AttemptStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("totalMarks", sa.Float(), nullable=True),
        sa.Column("percentage", sa.Float(), nullable=True),
        sa.Column("grade", sa.String(), nullable=True),
        sa.Column("timeSpentSeconds", sa.Integer(), nullable=True),
        sa.Column("awayEvents", sa.Integer(), nullable=True),
        sa.Column(
            "startedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completedAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessmentId"],
            ["Assessment.id"],
        ),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "AssessmentAttempt_student_assessment_idx",
        "AssessmentAttempt",
        ["studentId", "assessmentId"],
        unique=False,
    )
    op.create_index(
        "AssessmentAttempt_student_status_completed_idx",
        "AssessmentAttempt",
        ["studentId", "status", "completedAt"],
        unique=False,
    )
    op.create_index(
        "AssessmentAttempt_student_status_idx",
        "AssessmentAttempt",
        ["studentId", "status"],
        unique=False,
    )
    op.create_table(
        "NotificationPreference",
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("studyReminders", sa.Boolean(), nullable=False),
        sa.Column("streakReminders", sa.Boolean(), nullable=False),
        sa.Column("announcements", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("userId"),
    )
    op.create_table(
        "PushSubscription",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("p256dh", sa.String(), nullable=False),
        sa.Column("auth", sa.String(), nullable=False),
        sa.Column("failureCount", sa.Integer(), nullable=False),
        sa.Column("deviceId", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_table(
        "ReminderLog",
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("dayKey", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("userId", "kind", "dayKey"),
    )
    op.create_table(
        "Session",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sessionToken", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sessionToken"),
    )
    op.create_table(
        "StudentAchievement",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("achievementId", sa.String(), nullable=False),
        sa.Column(
            "earnedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["achievementId"], ["Achievement.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("studentId", "achievementId"),
    )
    op.create_table(
        "StudyPlan",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column(
            "subjectIds", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "targetExam",
            sa.Enum(
                "WAEC",
                "JAMB",
                "NECO",
                "CUSTOM",
                name="ExamType",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("targetDate", sa.Date(), nullable=True),
        sa.Column("forceExamMode", sa.Boolean(), nullable=False),
        sa.Column("studyDays", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column("weekdayMinutes", sa.Integer(), nullable=False),
        sa.Column("weekendMinutes", sa.Integer(), nullable=False),
        sa.Column("plannedThrough", sa.Date(), nullable=True),
        sa.Column("lastReplannedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("overload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "StudyPlan_student_active_idx",
        "StudyPlan",
        ["studentId", "isActive"],
        unique=False,
    )
    op.create_table(
        "Subscription",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "FREEMIUM",
                "STANDARD",
                "PREMIUM",
                name="SubscriptionTier",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "period",
            sa.Enum("MONTHLY", "YEARLY", name="BillingPeriod", create_constraint=True),
            nullable=False,
        ),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("amountKobo", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "FAILED",
                "ABANDONED",
                "REVOKED",
                name="SubscriptionStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "PAYSTACK", "COMP", name="SubscriptionSource", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("paidAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("startsAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("endsAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grantedById", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grantedById"],
            ["Admin.id"],
        ),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    op.create_index("Subscription_status_idx", "Subscription", ["status"], unique=False)
    op.create_index(
        "Subscription_user_ends_idx", "Subscription", ["userId", "endsAt"], unique=False
    )
    op.create_table(
        "Topic",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column("curriculumLevelId", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("orderIndex", sa.Integer(), nullable=False),
        sa.Column("estimatedMinutes", sa.Integer(), nullable=False),
        sa.Column("waecWeight", sa.Float(), nullable=False),
        sa.Column("jambWeight", sa.Float(), nullable=False),
        sa.Column("prerequisiteTopicId", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["curriculumLevelId"],
            ["CurriculumLevel.id"],
        ),
        sa.ForeignKeyConstraint(["subjectId"], ["Subject.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subjectId", "slug"),
    )
    op.create_table(
        "UserDevice",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column(
            "lastSeenAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revokedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "UserDevice_userId_revokedAt_idx",
        "UserDevice",
        ["userId", "revokedAt"],
        unique=False,
    )
    op.create_table(
        "LearningEvent",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=True),
        sa.Column("topicId", sa.String(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "QUESTION_ANSWERED",
                "QUIZ_ABANDONED",
                "LESSON_BLOCK_COMPLETED",
                "LESSON_COMPLETED",
                "CARD_REVIEWED",
                "PRETEST_PASSED",
                name="LearningEventKind",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BASIC",
                "INTERMEDIATE",
                "ADVANCED",
                name="Difficulty",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("seconds", sa.Float(), nullable=True),
        sa.Column("sourceId", sa.String(), nullable=True),
        sa.Column(
            "occurredAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topicId"],
            ["Topic.id"],
        ),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index(
        "LearningEvent_student_seq_idx",
        "LearningEvent",
        ["studentId", "seq"],
        unique=False,
    )
    op.create_index(
        "LearningEvent_student_topic_seq_idx",
        "LearningEvent",
        ["studentId", "topicId", "seq"],
        unique=False,
    )
    op.create_table(
        "PerformanceMetric",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=False),
        sa.Column(
            "masteryLevel",
            sa.Enum(
                "WEAK",
                "DEVELOPING",
                "COMPETENT",
                "STRONG",
                name="MasteryLevel",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("pretestPassedAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topicId"],
            ["Topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("studentId", "subjectId", "topicId"),
    )
    op.create_table(
        "Question",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=True),
        sa.Column(
            "examType",
            sa.Enum(
                "WAEC",
                "JAMB",
                "NECO",
                "CUSTOM",
                name="ExamType",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("examYear", sa.Integer(), nullable=True),
        sa.Column("questionNumber", sa.Integer(), nullable=True),
        sa.Column("questionText", sa.Text(), nullable=False),
        sa.Column("questionImageUrl", sa.String(), nullable=True),
        sa.Column(
            "questionType",
            sa.Enum(
                "OBJECTIVE",
                "THEORY",
                "FILL_IN_BLANK",
                name="QuestionType",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correctAnswer", sa.String(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("explanationImageUrl", sa.String(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BASIC",
                "INTERMEDIATE",
                "ADVANCED",
                name="Difficulty",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("marks", sa.Integer(), nullable=False),
        sa.Column("timeEstimateSeconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topicId"],
            ["Topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "Question_exam_year_idx", "Question", ["examType", "examYear"], unique=False
    )
    op.create_index(
        "Question_subject_difficulty_idx",
        "Question",
        ["subjectId", "difficulty"],
        unique=False,
    )
    op.create_index(
        "Question_subject_exam_year_idx",
        "Question",
        ["subjectId", "examType", "examYear"],
        unique=False,
    )
    op.create_index(
        "Question_subject_topic_idx", "Question", ["subjectId", "topicId"], unique=False
    )
    op.create_index(
        "Question_subject_type_exam_idx",
        "Question",
        ["subjectId", "questionType", "examType"],
        unique=False,
    )
    op.create_index(
        "Question_subject_type_idx",
        "Question",
        ["subjectId", "questionType"],
        unique=False,
    )
    op.create_table(
        "StudyPlanItem",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studyPlanId", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=True),
        sa.Column(
            "activityType",
            sa.Enum(
                "LESSON",
                "PRACTICE",
                "REVISION",
                "MOCK_EXAM",
                "PAST_QUESTIONS",
                name="PlanItemActivity",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("durationMinutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "SKIPPED",
                "MISSED",
                name="PlanItemStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("completedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "completionSource",
            sa.Enum(
                "AUTO", "MANUAL", name="PlanCompletionSource", create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("carriedFromDate", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["studyPlanId"], ["StudyPlan.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topicId"],
            ["Topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "StudyPlanPosition",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studyPlanId", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["studyPlanId"], ["StudyPlan.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topicId"],
            ["Topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("studyPlanId", "subjectId"),
    )
    op.create_table(
        "Subtopic",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("orderIndex", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["topicId"], ["Topic.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "TopicEdge",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("prereqTopicId", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PREREQUISITE",
                "STRONG_RELATED",
                "RELATED",
                name="EdgeKind",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["prereqTopicId"], ["Topic.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topicId"], ["Topic.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prereqTopicId", "topicId"),
    )
    op.create_table(
        "TopicMastery",
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=False),
        sa.Column("accOutcome", sa.Float(), nullable=False),
        sa.Column("accMass", sa.Float(), nullable=False),
        sa.Column("accObservations", sa.Integer(), nullable=False),
        sa.Column("lessonOutcome", sa.Float(), nullable=False),
        sa.Column("lessonMass", sa.Float(), nullable=False),
        sa.Column("lessonObservations", sa.Integer(), nullable=False),
        sa.Column("srsOutcome", sa.Float(), nullable=False),
        sa.Column("srsMass", sa.Float(), nullable=False),
        sa.Column("srsObservations", sa.Integer(), nullable=False),
        sa.Column("abandonCount", sa.Integer(), nullable=False),
        sa.Column("decayAnchor", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lastEffortAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursorSeq", sa.BigInteger(), nullable=False),
        sa.Column("scoringVersion", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topicId"], ["Topic.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("studentId", "topicId"),
    )
    op.create_table(
        "AssessmentQuestion",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("assessmentId", sa.String(), nullable=False),
        sa.Column("questionId", sa.String(), nullable=False),
        sa.Column("orderIndex", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessmentId"], ["Assessment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["questionId"],
            ["Question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessmentId", "questionId"),
    )
    op.create_table(
        "Lesson",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("subtopicId", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("keyPoints", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "workedExamples", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("examTips", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mnemonics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "knowledgeChecks", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "prerequisites", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "revisionDays", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("createdBy", sa.String(), nullable=True),
        sa.Column("passMarkPercent", sa.Integer(), nullable=False),
        sa.Column("practiceCount", sa.Integer(), nullable=False),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subtopicId"], ["Subtopic.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ProviderQuestion",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fetchId", sa.String(), nullable=False),
        sa.Column("providerQuestionId", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROMOTED",
                "REJECTED",
                name="ProviderQuestionStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "rejectionReasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("questionId", sa.String(), nullable=True),
        sa.Column("mapperVersion", sa.Integer(), nullable=True),
        sa.Column("promotedAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["fetchId"], ["ProviderFetch.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["questionId"],
            ["Question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fetchId", "fingerprint"),
        sa.UniqueConstraint("fetchId", "providerQuestionId"),
        sa.UniqueConstraint("questionId"),
    )
    op.create_table(
        "QuestionResponse",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("attemptId", sa.String(), nullable=False),
        sa.Column("questionId", sa.String(), nullable=False),
        sa.Column("selectedAnswer", sa.String(), nullable=True),
        sa.Column("isCorrect", sa.Boolean(), nullable=False),
        sa.Column("timeSpentSeconds", sa.Integer(), nullable=True),
        sa.Column("flaggedForReview", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attemptId"], ["AssessmentAttempt.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["questionId"],
            ["Question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attemptId", "questionId"),
    )
    op.create_table(
        "FlashcardDeck",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=True),
        sa.Column("topicId", sa.String(), nullable=True),
        sa.Column("lessonId", sa.String(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "AUTHORED",
                "LESSON",
                "AI",
                name="FlashcardSource",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("createdBy", sa.String(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["createdBy"],
            ["User.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lessonId"],
            ["Lesson.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topicId"],
            ["Topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lessonId", "source"),
    )
    op.create_table(
        "LessonResource",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("lessonId", sa.String(), nullable=False),
        sa.Column("resourceType", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["lessonId"], ["Lesson.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "StudentProgress",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("subjectId", sa.String(), nullable=False),
        sa.Column("topicId", sa.String(), nullable=False),
        sa.Column("lessonId", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                name="ProgressStatus",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("completionPercent", sa.Integer(), nullable=False),
        sa.Column("timeSpentMinutes", sa.Integer(), nullable=False),
        sa.Column("lastAccessedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "checkpointData", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("masteryScore", sa.Integer(), nullable=True),
        sa.Column("revisionDueAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lessonId"],
            ["Lesson.id"],
        ),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subjectId"],
            ["Subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topicId"],
            ["Topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("studentId", "subjectId", "topicId", "lessonId"),
    )
    op.create_table(
        "Flashcard",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("deckId", sa.String(), nullable=False),
        sa.Column(
            "cardType",
            sa.Enum(
                "DEFINITION",
                "FORMULA",
                "IMAGE",
                "DIAGRAM",
                "FILL_IN_BLANK",
                "COMPARE_CONTRAST",
                "TRUE_FALSE",
                "SCENARIO",
                "PROCESS",
                name="FlashcardType",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sourceKey", sa.String(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum(
                "BASIC",
                "INTERMEDIATE",
                "ADVANCED",
                name="Difficulty",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["deckId"], ["FlashcardDeck.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deckId", "sourceKey"),
    )
    op.create_table(
        "FlashcardEnrollment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("deckId", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["deckId"], ["FlashcardDeck.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("studentId", "deckId"),
    )
    op.create_table(
        "FlashcardReview",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("flashcardId", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "NEW",
                "LEARNING",
                "REVIEW",
                "RELEARNING",
                name="FlashcardState",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("easeFactor", sa.Float(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("intervalDays", sa.Float(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("retention", sa.Float(), nullable=False),
        sa.Column("dueAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lastReviewedAt", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["flashcardId"], ["Flashcard.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("studentId", "flashcardId"),
    )
    op.create_table(
        "FlashcardReviewLog",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("studentId", sa.String(), nullable=False),
        sa.Column("flashcardId", sa.String(), nullable=False),
        sa.Column(
            "rating",
            sa.Enum(
                "AGAIN",
                "HARD",
                "GOOD",
                "EASY",
                name="ReviewRating",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("responseTimeMs", sa.Integer(), nullable=True),
        sa.Column("scheduledDays", sa.Float(), nullable=True),
        sa.Column("objectiveCorrect", sa.Boolean(), nullable=True),
        sa.Column(
            "reviewedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["flashcardId"], ["Flashcard.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["studentId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("FlashcardReviewLog")
    op.drop_table("FlashcardReview")
    op.drop_table("FlashcardEnrollment")
    op.drop_table("Flashcard")
    op.drop_table("StudentProgress")
    op.drop_table("LessonResource")
    op.drop_table("FlashcardDeck")
    op.drop_table("QuestionResponse")
    op.drop_table("ProviderQuestion")
    op.drop_table("Lesson")
    op.drop_table("AssessmentQuestion")
    op.drop_table("TopicMastery")
    op.drop_table("TopicEdge")
    op.drop_table("Subtopic")
    op.drop_table("StudyPlanPosition")
    op.drop_table("StudyPlanItem")
    op.drop_index("Question_subject_type_idx", table_name="Question")
    op.drop_index("Question_subject_type_exam_idx", table_name="Question")
    op.drop_index("Question_subject_topic_idx", table_name="Question")
    op.drop_index("Question_subject_exam_year_idx", table_name="Question")
    op.drop_index("Question_subject_difficulty_idx", table_name="Question")
    op.drop_index("Question_exam_year_idx", table_name="Question")
    op.drop_table("Question")
    op.drop_table("PerformanceMetric")
    op.drop_index("LearningEvent_student_topic_seq_idx", table_name="LearningEvent")
    op.drop_index("LearningEvent_student_seq_idx", table_name="LearningEvent")
    op.drop_table("LearningEvent")
    op.drop_index("UserDevice_userId_revokedAt_idx", table_name="UserDevice")
    op.drop_table("UserDevice")
    op.drop_table("Topic")
    op.drop_index("Subscription_user_ends_idx", table_name="Subscription")
    op.drop_index("Subscription_status_idx", table_name="Subscription")
    op.drop_table("Subscription")
    op.drop_index("StudyPlan_student_active_idx", table_name="StudyPlan")
    op.drop_table("StudyPlan")
    op.drop_table("StudentAchievement")
    op.drop_table("Session")
    op.drop_table("ReminderLog")
    op.drop_table("PushSubscription")
    op.drop_table("NotificationPreference")
    op.drop_index(
        "AssessmentAttempt_student_status_idx", table_name="AssessmentAttempt"
    )
    op.drop_index(
        "AssessmentAttempt_student_status_completed_idx", table_name="AssessmentAttempt"
    )
    op.drop_index(
        "AssessmentAttempt_student_assessment_idx", table_name="AssessmentAttempt"
    )
    op.drop_table("AssessmentAttempt")
    op.drop_table("AnnouncementDismissal")
    op.drop_table("Account")
    op.drop_index("User_tier_idx", table_name="User")
    op.drop_index("User_state_idx", table_name="User")
    op.drop_index("User_isActive_idx", table_name="User")
    op.drop_index("User_classLevel_track_idx", table_name="User")
    op.drop_table("User")
    op.drop_table("SubjectResource")
    op.drop_table("ProviderFetch")
    op.drop_table("ProviderCatalogue")
    op.drop_table("CurriculumLevel")
    op.drop_table("Assessment")
    op.drop_table("AnnouncementDelivery")
    op.drop_table("AdminAudit")
    op.drop_table("VerificationToken")
    op.drop_table("Subject")
    op.drop_table("School")
    op.drop_table("ProviderState")
    op.drop_table("PaystackEvent")
    op.drop_table("JambCombination")
    op.drop_table("Announcement")
    op.drop_table("Admin")
    op.drop_table("Achievement")
    op.drop_table("AcademicTerm")
    # ### end Alembic commands ###
