name: Workflow for ScholarScrib API Development

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  push:
    branches:
      - develop

env:
  SCHOLARSCRIB_ENV: dev

jobs:

  build_and_lint:
    uses: ./.github/workflows/build_and_lint.yml
    with:
      python-version-file: ".python-version"
    secrets: inherit
